call pathogen#infect()
call pathogen#incubate()
" Filetype detection.
au BufRead,BufNewFile *xensource.log* set filetype=messages
au BufRead,BufNewFile *SMlog* set filetype=smlog

" General editor settings.
syntax on
filetype plugin indent on

" Filetype-specific settings.
au FileType ocaml setl sw=2 sts=2 ts=2 tw=0 wrapmargin=0 noexpandtab
au FileType javascript setl sw=4 sts=4 ts=4 tw=0 wrapmargin=0 expandtab
au FileType python setl sw=4 sts=4 ts=4 expandtab
au FileType ruby setl sw=4 sts=4 ts=4 expandtab
au FileType sh setl sw=4 sts=4 ts=4 expandtab
au FileType css setl sw=4 sts=4 ts=4 expandtab
au FileType html setl sw=4 sts=4 ts=4 expandtab
au FileType vim setl sw=4 sts=4 ts=4 expandtab
au FileType c setl sw=4 sts=4 ts=4 expandtab
au FileType erlang setl sw=4 sts=4 ts=4 expandtab
au FileType haskell setl sw=4 sts=4 ts=4 expandtab

" Visual settings.
colorscheme desert
set statusline=%t%m%r%h%w\ \ \ [BUF=%02n]\ \ \ [TYPE=%Y]\ \ \ [POS=%03l,%03c(%03v)][%03p%%]\ \ \ [LEN=%L]
set listchars=tab:.-,trail:>,eol:$
set laststatus=2
set cursorline
set hls
set list
set incsearch

" Tab completion.
set wildmode=longest:full
set wildmenu
